### PR TITLE
Refactor: Migrate from deprecated WebClient to async HttpClient

### PR DESCRIPTION
**Pull request by nt-7**
# Overview

This pull request addresses the issue of using the deprecated WebClient class in the current implementation.

WebClient is not recommended for use in .NET. Moreover, it is [not supported in Blazor](https://stackoverflow.com/questions/56284192/webclient-not-supported). This PR replaces [deprecated WebClient with the recommended HttpClient class](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient?view=net-6.0#remarks) and updates the relevant method to reflect the change to asynchronous methods.

## Changes

- Replaced [the implementation using WebClient](https://github.com/microsoft/Tokenizer/blob/main/Tokenizer_C%23/TokenizerLib/TokenizerBuilder.cs#L204) with HttpClient implementation
- Updated synchronous method name to their asynchronous counterparts, adding "Async" suffix
- Updated those method calls to use the async/await pattern

## Reasons for the change (Background)

- WebClient has been already **deprecated** in .NET.
https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated
https://learn.microsoft.com/en-us/dotnet/api/system.net.webclient?view=net-7.0#remarks
- The library cannot be used in Blazor projects, because WebClient is [not supported in Blazor](https://stackoverflow.com/questions/56284192/webclient-not-supported).

## Testing
It passed successfully all 14 tests and the original sample code.

### CODE REVIEW

**Comment by nt-7** [comment]
@microsoft-github-policy-service agree

**Comment by nt-7** [comment]
@shengyfu @djyou, could you review this if you can? Or, would be happy to assign a reviewer.

**Comment by shengyfu** [comment]
Thanks for contributing.

**Review by shengyfu — APPROVED** [review]

**Review by shengyfu — APPROVED** [review]

**Comment by nt-7** [comment]
As side notes, next published [Nuget version](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-basics) including this change should preferably be a **major** version such as **2.x.x**. This is because it includes some breaking changes to the method.

**Pull request merged**
